PAGE_SIZE: 100
BASE_URL: 'https://api.fina.org/fina/'
DISCIPLINE: 'SW'
GROUP: 'FINA'
COLS_REMOVE:
  - 'metadata.watchNowURL'
  - 'metadata.showGMSLogin'
  - 'metadata.ticketsURL'
EVENT_COLS:
- 'Id'
- 'OfficialName'
- 'Name'
- 'City'
- 'CountryCode'
- 'CountryId'
- 'CountryName'
- 'EventTypeName'
- 'EventTypeId'
- 'OdfCompetitionCode'
- 'PoolConfiguration'
- 'QualificationForEventTypes'
- 'RegionName'
- 'ResultsReceived'
- 'Series'
- 'Sports'
- 'From'
- 'To'
- 'TimeZone'
BASE_PATH: './data/'